[tool.isort]
force_grid_wrap = 0
include_trailing_comma = "true"
line_length = 128
lines_after_imports = 2
multi_line_output = 3
use_parentheses = "true"
ensure_newline_before_comments = "true"
skip_glob = "*.pyx"
skip_gitignore = "true"


[tool.black]
line-length = 128


[tool.pytest.ini_options]
testpaths = "tests/"
addopts = """
-v 
-p no:warning
-s
-x 
--cov src
--cov-fail-under=90
--html=reports/unittest/index.html
--cov-report=html:reports/coverage
--cov-report=term-missing
--cov-config=tests/.coveragerc
"""
