# Below will be replaced by environment variables defined in env.sh
appName: ""
k8sNamespace: ""
groupName: ""
chartVersion: ""

nameOverride: ""
fullnameOverride: ""

locust_host: ""
locust_users: ""
locust_spawn_rate: ""
locust_run_time: ""
locust_locustfile: ""
locust_webui: ""
locust_webui_workers: ""
locust_slave: ""

S3Url: "http://192.168.60.70:31333/" # change to rnd's s3 url
uploadS3: ""
accountS3: ""
passwordS3: ""

loadtest:
  # loadtest.name -- a name used for resources and settings in this load test
  name: example
  # loadtest.locust_locustfile_configmap -- name of a configmap containing your locustfile
  locust_locustfile_configmap: ""
  # loadtest.locust_lib_configmap -- name of a configmap containing your lib
  locust_lib_configmap: ""
  # loadtest.pip_packages -- a list of extra python pip packages to install
  pip_packages: [ diskcache, http://ess-repos01.wisers.com:8081/repository/pypi-server-hosted/packages/datamgr-common/0.1.0/datamgr_common-0.1.0-py3-none-any.whl ]
  # loadtest.environment -- environment variables used in the load test
  environment: {}
    # VAR: VALUE

image:
  repository: ess-repos01.wisers.com:8889/locust
  tag: 1.5.3-dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  annotations: {}
  extraLabels: {}

master:
  # master.image -- A custom docker image including tag
  image: ""
  # master.logLevel -- Log level. Can be INFO or DEBUG
  logLevel: INFO
  # master.resources -- resources for the locust master
  resources: {}
    # limits:
    #   cpu: 2000m
    #   memory: 1024Mi
    # requests:
    #   cpu: 1000m
    #   memory: 1024Mi
  serviceAccountAnnotations: {}
  # master.args_include_default -- Whether to include default command args
  args_include_default: true
  command:
    - sh
    - /config/docker-entrypoint.sh
  strategy:
    type: RollingUpdate
  # master.pdb.enabled -- Whether to create a PodDisruptionBudget for the master pod
  pdb:
    enabled: false

worker:
  # worker.image -- A custom docker image including tag
  image: ""
  # worker.logLevel -- Log level. Can be INFO or DEBUG
  logLevel: INFO
  replicas: 1
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 40
  # worker.resources -- resources for the locust worker
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 256Mi
    # requests:
    #   cpu: 500m
    #   memory: 256Mi
  serviceAccountAnnotations: {}
  # worker.args_include_default -- Whether to include default command args
  args_include_default: true
  command:
    - sh
    - /config/docker-entrypoint.sh
  strategy:
    type: RollingUpdate

imagePullSecrets: []

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  annotations: {}
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# extraConfigMaps -- Any extra configmaps to mount for the master and worker. Can be used for extra python packages
extraConfigMaps: {}
nodeSelector: {}
tolerations: []
affinity: {}
extraLabels: {}
