{{- if .Values.locust_webui -}}
# rbac.yaml is only used by .Values.locust_webui == false
{{- else -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.fullnameOverride }}
  labels:
{{ include "locust.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.fullnameOverride }}
  namespace: {{ .Values.k8sNamespace }}
roleRef:
  kind: Role
  name: {{ .Values.fullnameOverride }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.fullnameOverride }}
  labels:
{{ include "locust.labels" . | indent 4 }}
rules:
- apiGroups: ["","metrics.k8s.io"]
  resources:
  - pods
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fullnameOverride }}
  labels:
{{ include "locust.labels" . | indent 4 }}
---
{{- end }}