{{- if .Values.cronjob.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
{{- template "commonMeta" . }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.job.name }}
            image: {{ .Values.cronjob.imageRepository }}
            command:
            - "sh"
            - "-c"
            - {{ .Values.cronjob.ShellCommand | quote }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
{{- end -}}
